- name: Create VM for k3s worker [count {{ groups['k3s-worker'] | length }}]
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ vmid_template }}"
    newid: "{{ hostvars[item].ansible_vmid }}"
    name: "{{ hostvars[item].inventory_hostname }}"
    clone: "{{ hostvars[item].inventory_hostname }}"
    state: present
    timeout: "{{ vm_timeout }}"
  loop: "{{ groups['k3s-worker'] }}"

- name: Setting VM config
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ hostvars[item].ansible_vmid }}"
    memory: "{{ vm_server_memory }}"
    cores: "{{ vm_server_cores }}"
    ide:
      ide2: '{{ vm_storage }}:cloudinit,format=qcow2'
    ciuser: "{{ vm_ciuser }}"
    sshkeys: "{{ vm_sshkeys }}"
    searchdomains: "{{ vm_domain }}"
    nameservers: "{{ vm_dns }}"
    ipconfig:
      ipconfig0: "ip={{ hostvars[item].ansible_host }}/{{ vm_mask }},gw={{ vm_gw }}"
    update: true
  loop: "{{ groups['k3s-worker'] }}"

- name: Resiza disk in shell
  ansible.builtin.command: qm disk resize {{ hostvars[item].ansible_vmid }} scsi0 {{ vm_server_disk }}G
  changed_when: lvs | grep vm-"{{ hostvars[item].ansible_vmid }}"-disk-0 | awk '{print $4}' | sed 's/g//' | cut -d'.' -f1 != "{{ vm_server_disk }}"
  ignore_errors: true
  loop: "{{ groups['k3s-worker'] }}"